language: python

env:
  # earliest and latest supported; last release of every year; 12.1 for txsocksx.http
  - TWISTED=Twisted==10.1
  - TWISTED=Twisted==10.2
  - TWISTED=Twisted==11.1
  - TWISTED=Twisted==12.1
  - TWISTED=Twisted==12.3
  - TWISTED=Twisted==13.2
  - TWISTED=svn+svn://svn.twistedmatrix.com/svn/Twisted/trunk

python:
  - 2.6
  - 2.7
  - pypy

matrix:
  allow_failures:
    # pypy is a bit sporadic
    - python: pypy

install:
  - pip install $TWISTED pyOpenSSL coveralls --use-mirrors
  - pip install -r requirements.txt --use-mirrors

script: coverage run $(which trial) txsocksx
after_success: "coveralls"
